---
ROUTE_ID_01: "IDC-Kubernetes-Master01"
ROUTE_ID_02: "IDC-Kubernetes-Master02"
ROUTE_ID_03: "IDC-Kubernetes-Master03"

VRRP_INSTANSE: "IDC-Kubernetes-Master"
INTERFACE: "ens192"
VIRTUAL_ROUTE_ID: "97"

PRIOTIRY_MASTER: "100"
PRIOTIRY_BACKUP_01: "70"
PRIOTIRY_BACKUP_02: "40"

AUTH_PASS: "IDC-K8S-PROD"
VIRTUAL_IP: "10.3.3.230"

MASTER_IP: “10.3.3.231”
BACKUP01_IP: “10.3.3.232”
BACKUP02_IP: “10.3.3.233”
