---
- name: stop swap
  shell: 'swapoff -a'
 
- name: disable load swap on system starting
  lineinfile:
    path: /etc/fstab
    regexp: '^/dev/mapper/centos-swap'
    line: '#/dev/mapper/centos-swap swap                    swap    defaults        0 0'
